function f = f_fun(M,b,gravity,l,m,q)
%F_FUN
%    F = F_FUN(M,B,GRAVITY,L,m,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    19-Jun-2022 04:02:16

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q3);
t3 = sin(q3);
t4 = q4.^2;
t5 = t3.^2;
t6 = m.*t5;
t7 = M+t6;
t8 = 1.0./t7;
f = [q2;-t8.*(b.*q2+gravity.*m.*t2.*t3-l.*m.*t3.*t4);q4;(t8.*(gravity.*t3.*(M+m)+b.*q2.*t2-l.*m.*t2.*t3.*t4))./l];
