function h = h_fun(q)
%H_FUN
%    H = H_FUN(Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    19-Jun-2022 04:02:21

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

h = q3;
