function LgLfh = LgLfh_fun(M,l,m,q3)
%LgLfh_fun
%    LgLfh = LgLfh_fun(M,L,m,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    19-Jun-2022 13:48:55

t2 = sin(q3);
t3 = t2.^2;
t4 = m.*t3;
t5 = M+t4;
t6 = 1.0./t5;
LgLfh = t6-(t6.*cos(q3))./l;
